---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          imagePullPolicy: Never
          image: "demo:latest"
          ports:
            - containerPort: 4000
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "4000"
            - name: SECRET_KEY_BASE
              value: "/uMXbd4AyFgZ0acGsd95Oq8DphwRC8GDjWzcCLIS8XjE73pCl1iHDbP0IMgafi0x"
